
export const metadata = {
    title:"Sign in - GitHub Unwrapped",
    description: "Generated by create next app",
  };
  
  export default async function RootLayout({ children }) {
  
    return (
      <>
          {children}   
      </>
    );
  }
  