
export const metadata = {
  title:"Sign out - GitHub Unwrapped",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <>
        {children}   
    </>
  );
}
